
openapi: 3.0.3
info:
  title: Katamari API
  version: "1.0.0"
  description: |
    Chainlitフォーク上で動作する補助API群
    現時点で公開中なのは `/metrics` と `/healthz`
servers:
  - url: http://localhost:8787
paths:
  /api/chat:
    post:
      summary: Chat (SSE/JSON)
      description: "未実装（計画中）"
      deprecated: true
      x-status: planned
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [model, messages]
              properties:
                model: { type: string }
                stream: { type: boolean, default: true }
                messages:
                  type: array
                  items:
                    type: object
                    required: [role, content]
                    properties:
                      role: { type: string, enum: [system, user, assistant] }
                      content: { type: string }
                meta:
                  type: object
                  properties:
                    chain: { type: string }
                opts:
                  type: object
      responses:
        "200":
          description: OK (SSE or JSON)
  /api/trim:
    post:
      summary: Context trimming
      description: "未実装（計画中）"
      deprecated: true
      x-status: planned
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      role: { type: string }
                      content: { type: string }
                targetTokens: { type: integer, default: 4096 }
      responses: { "200": { description: OK } }
  /api/persona/compile:
    post:
      summary: Persona YAML -> System prompt
      description: "未実装（計画中）"
      deprecated: true
      x-status: planned
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yaml: { type: string }
      responses: { "200": { description: OK } }
  /api/chain/run:
    post:
      summary: Run chain (reflect)
      description: "未実装（計画中）"
      deprecated: true
      x-status: planned
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chain: { type: string }
                messages:
                  type: array
                  items:
                    type: object
                    properties:
                      role: { type: string }
                      content: { type: string }
      responses: { "200": { description: OK (SSE) } }
  /api/evolve:
    post:
      summary: Prompt evolution (M2)
      description: "未実装（計画中）"
      deprecated: true
      x-status: planned
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt: { type: string }
                objective: { type: string }
                pop: { type: integer, default: 6 }
                gen: { type: integer, default: 5 }
                evaluator:
                  type: string
                  enum: [bertscore, rouge, rules]
      responses: { "200": { description: OK } }
  /api/models:
    get:
      summary: List models
      description: "未実装（計画中）"
      deprecated: true
      x-status: planned
      responses: { "200": { description: OK } }
  /metrics:
    get:
      summary: Prometheus metrics
      responses: { "200": { description: OK } }
  /healthz:
    get:
      summary: Health check
      responses: { "200": { description: OK } }
